language: cpp
compiler:
  - gcc
OS:
  - linux


before_install:
  - pip install --user cpp-coveralls
  


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-7

script:
- ./configure --enable-gcov
- gcov --help
- sudo apt update
- sudo apt install build-essential
- sudo apt-get install manpages-dev
- gcc --version

- mkdir _build
- cd _build
- cmake ../
- cd ..
- cmake --build _build

after_success:
- coveralls --verbose

script:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
- coveralls --verbose
